language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: YdB4NRGZcCrHFWzRvUv8gosOpFQYJGTmaxNH1rgrvM7N0ZNh3RLEL03MN3BS0xfNFZOn6SDMiiGp9emynEDn5pBQ1meItXmWzjQWDWOn4uwSXwR2FFFLNFQTnhu+IhZJtoMKnGcPwgqcom/lEc3xMw8pXD6mnAVHyWmuskGbvKRkd7paghZqYgCySECUJ9Hyie0wJuzH0LkqqxzRcAbrbO9GMqoJTgA2emOrJZPNt7u0dD4IesaWH0vsWq3dEBO3ga5LdWlqcVw2BpzQfN8uXO+iILtosflCtFkm1Wa4PZWTDhqak2hKiXFvoyjH997U08A1Wbqt0A3Po/nAHMTSBp9XaSO9qsYMWvvGGW3iwIe8IQjGsZkRA6SACMn0Kz4AacaZjzmrEhrYjMCg1p+aad9ptDT4z79CXzyzQ6bSrmjEqInn5LlQsvN0d7GZ0BRItKezBMlqZgd0ZOff0uU5ZLxIcL1o0KIsWA+tryro+khy1C2tGHxd1Y44iOTBcyY2Iic4VYbqi62KU+jZ9oBO7lNRUp3mw9FHHAg44wb1bm310I7BaQizOyT0vqL3l+9TahW0nep8r8MoTs87lPGDTepIpzhpTLAlz6odUwtBucCZEjaKKWhh/aCT3V682SMUrZTL7thBykG4fb8SrJSXgp99xdqk7yhQcjcEjiVo36U=
  app: jalgoarena-ui
  on:
    repo: spolnik/JAlgoArena-UI
branches:
  only:
  - master
