language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: C/8p33sJxppaqLAC8NkzpP3IQjM28HO1lSsMo6Jd5vcwEbYZMqd7e/NdY5UShRK5TQCDKhxwU9GnUR6tDh5uZNuHkXkCrlZxb253+nLrEOiYIYpIoMBnHns4OIit1IfaDFmvkURTz/iHMJTow+mYHSvSKvUJsKkd2unsEOOIUWniZsSIZs1ec23pHW4k9ECT/qb8rM35FqDy73WBVGXdXE9uA0mYHzsGml5rVS+5UuZxG1+9ogFtWYIRrl/BLDr7v7QSMwIHQCedvUuQJQfK6xTc6tAzEIblp/zATmCgRTa78suvHSWJsH1DtKrQoXpKNHR62T1yp5kV4CXDzlMwKuO9ZNKUBeiWoDYKbmoFeGPE4CB33f/H54PJJv3RuYyrKqjGiYptg1BQBUfK/sbTCiSTt42pwt8B76KFCk+LgM13T+xkLHxDuQPNiLUss7oBbfkN54DLeHLu3cBd8zaaAMoGtU1uCQXJ6R7eran0O2t/Ma6kHPqKq7iZp+yQ4ThsKwZ0Crn+hMCMss0Z3mtiOiKgtgmxi6QrwoDc/PKFHh8Ev1iSmeJiycoTlg+KLLvdM7B7HcEHy6xbOZkAexpBXxvbI/W65QIpA1yaf3r5G2X0YCOY9GfenwRbKPn7Wwd82oYc1wFKjIgYiA7Jv4ho0ZgwmW2P1mwJ7Squ+ldUCJw=
  app: jalgoarena-ui
  on:
    repo: spolnik/JAlgoArena-UI
branches:
  only:
  - master
